spring:
  application:
    name: justmall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8333
  thymeleaf:
    cache: false
#  session:
#    store-type: redis
#  redis:
#    host: ${ipAddr}

ipAddr: 192.168.6.189
server:
  port: 13000
